# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFPsgI3XJ7sTA0N-ztMaQUCyEerK7kek
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os
import json
from google import genai
from google.genai import types

# Initialize your FastAPI app
app = FastAPI()

# Allow your frontend website to talk to this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, change this to your Vercel website URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the GenAI client
# It will automatically look for the "GEMINI_API_KEY" in Render's Environment Variables!
client = genai.Client()

# Define what the incoming data from the website should look like
class ComplaintRequest(BaseModel):
    text: str

# Create the API Endpoint
@app.post("/api/classify")
async def analyze_complaint_g3_flash(request: ComplaintRequest):
    # The Prompt
    prompt = f"""
    You are an AI dispatcher for a Philippine Barangay.
    Analyze the following complaint: "{request.text}"

    Categorize it strictly into one of these Incident Types:
    [Theft & Robbery, Physical Injury, Fire & Disaster, Medical Emergency, VAWC, Public Disturbance, General Incident]

    And categorize it strictly into one of these Urgency Levels:
    [Critical, High, Medium, Low]
    """

    try:
        # Call Gemini 3 Flash and force a JSON output
        response = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema={
                    "type": "OBJECT",
                    "properties": {
                        "incident_type": {
                            "type": "STRING",
                            "description": "The classified incident type."
                        },
                        "urgency_level": {
                            "type": "STRING",
                            "description": "The classified urgency level."
                        }
                    },
                    "required": ["incident_type", "urgency_level"]
                },
                thinking_config=types.ThinkingConfig(
                    thinking_level=types.ThinkingLevel.LOW
                )
            ),
        )

        # Parse the JSON string back into a Python dictionary and send it to the website
        return json.loads(response.text)

    except Exception as e:
        return {"error": str(e)}